id: P010689
initial_creation_type: ocr
created_at: 30/03/2020
last_modified_at: 2021-12-20 10:20:00.709940
source_metadata:
  id: bdr:W00KG01646
  title: སྤྲོས་མེད་རྒྱུན་གྱི་ཉམས་ལེན་ཀུ་སཱ་ལིའི་བདུད་རྩི
  author: ''
  volumes:
    55cda7dbd9634c68978a4a8e6174c4b7:
      image_group_id: I00KG02951
      title: ''
      volume_number: 1
      total_pages: 12
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
